# usermod -aG docker gitlab-runner

stages:
  - unit
  - build

variables:
  PROJECT_NAME: hyperf
  REGISTRY_URL: registry-docker.org
  GIT_SUBMODULE_STRATEGY: recursive

unit:
  stage: unit
  image: hyperf/docker-ci:latest
  resource_group: $CI_PROJECT_NAME
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - DOCKERFILE=unit.Dockerfile docker compose up -d --remove-orphans --build
    - sleep 30
    - docker exec $(basename $(pwd))-hyperf-1 go test ./... -v
  after_script:
    - docker compose down
  tags:
    - unit

build_test_docker:
  stage: build
  script:
    - docker build . -t $PROJECT_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:test
    - docker push $REGISTRY_URL/$PROJECT_NAME:test
  only:
    - test
  tags:
    - builder

build_docker:
  stage: build
  script:
    - docker build . -t $PROJECT_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker tag $PROJECT_NAME $REGISTRY_URL/$PROJECT_NAME:latest
    - docker push $REGISTRY_URL/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push $REGISTRY_URL/$PROJECT_NAME:latest
  only:
    - tags
  tags:
    - builder
