version: '3.7'
services:
  mysql:
    image: "mysql/mysql-server:8.0"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "hyperf"
    networks:
      - net
    volumes:
      - mysql-data:/var/lib/mysql
      - ./.github/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: "always"
  redis:
    image: "redis"
    command:
      - "redis-server"
      - "--databases 256"
    networks:
      - net
    volumes:
      - redis-data:/data
    restart: "always"
  hyperf:
    image: "hyperf/go-zero-skeleton:latest"
    build:
      context: "."
      dockerfile: "${DOCKERFILE:-Dockerfile}"
    depends_on:
      - mysql
      - redis
    ports:
      - "8888:8888"
    networks:
      - net
    restart: "always"
    deploy:
      replicas: 1
networks:
  net:
volumes:
  mysql-data:
  redis-data:
